In [1]:
# Library imports
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("ready to load data")

ready to load data

In [2]:
# Loading the data
data = pd.read_csv("../CSV data/loan_risk_prediction_dataset.csv")
print("data loaded successfully")

data loaded successfully

In [3]:
# head of the data
data.head(5)

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,NaN,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0

In [4]:
# quality check
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              5000 non-null   int64
 1   Income           4804 non-null   float64
 2   LoanAmount       5000 non-null   float64
 3   CreditScore      4806 non-null   float64
 4   YearsExperience  5000 non-null   int64
 5   Gender           5000 non-null   str
 6   Education        4802 non-null   str
 7   City             5000 non-null   str
 8   EmploymentType   5000 non-null   str
 9   LoanApproved     5000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 390.8 KB

In [5]:
# Duplicates check
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [6]:
# Check for duplicate records in dataset
data.duplicated().sum()

np.int64(0)

In [7]:
# Statystical overview
data.describe()

,Age,Income,LoanAmount,CreditScore,YearsExperience,LoanApproved
count,5000.000000,4804.000000,5000.000000,4806.000000,5000.000000,5000.000000
mean,43.584600,49738.123022,19870.768600,575.494590,19.599000,0.230200
std,14.919094,15101.361851,8046.542413,160.550839,11.516837,0.421003
min,18.000000,-3731.000000,-10059.000000,300.000000,0.000000,0.000000
25%,31.000000,39608.500000,14455.250000,433.000000,10.000000,0.000000
50%,43.000000,49488.000000,19842.500000,579.000000,20.000000,0.000000
75%,56.000000,59917.000000,25326.750000,712.000000,29.000000,0.000000
max,69.000000,99146.000000,48353.000000,849.000000,39.000000,1.000000

In [8]:
# factors for clustering

cluster_features = ["Age", "Income", "LoanAmount", "CreditScore", "YearsExperience"]

In [9]:
cluster_data = data[cluster_features].copy()

In [10]:
# remove missing values
cluster_data = cluster_data.dropna()

In [11]:
# quality check
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              5000 non-null   int64
 1   Income           4804 non-null   float64
 2   LoanAmount       5000 non-null   float64
 3   CreditScore      4806 non-null   float64
 4   YearsExperience  5000 non-null   int64
 5   Gender           5000 non-null   str
 6   Education        4802 non-null   str
 7   City             5000 non-null   str
 8   EmploymentType   5000 non-null   str
 9   LoanApproved     5000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 390.8 KB

In [13]:
# remove impossible negative values

cluster_data = cluster_data[(cluster_data["Income"] >= 0) & (cluster_data["LoanAmount"] >= 0) ]

In [15]:
cluster_data.head(7)

   Age   Income  LoanAmount  CreditScore  YearsExperience
0   56  48353.0     31258.0        675.0               20
1   69  57462.0     23262.0        586.0                6
2   46  44219.0     26530.0        781.0               26
3   32  56307.0     11531.0        549.0               11
4   60  37034.0     27871.0        500.0               19
5   25  47886.0     18106.0        835.0               13
6   38  54748.0     25374.0        760.0                9

In [20]:
scaler = MinMaxScaler()
X = scaler.fit(cluster_data).transform(cluster_data)
X = pd.DataFrame(X)
X.columns = cluster_data.columns

In [29]:
# KMeans Clustering started here
x = data
kMeans = KMeans(n_clusters=3, random_state=42, n_init=10)
y = kMeans.fit_predict(X)
print(y)

[2 2 0 ... 1 0 2]

In [24]:
cluster_data.head()

   Age   Income  LoanAmount  CreditScore  YearsExperience
0   56  48353.0     31258.0        675.0               20
1   69  57462.0     23262.0        586.0                6
2   46  44219.0     26530.0        781.0               26
3   32  56307.0     11531.0        549.0               11
4   60  37034.0     27871.0        500.0               19

In [40]:
# KMeans Clustering for k=5
x = data
kMeans = KMeans(n_clusters=5, random_state=42, n_init=10)
y = kMeans.fit_predict(X)
print(y)

[2 2 2 ... 4 2 1]

In [41]:
cluster_data["Cluster"] = y

In [35]:
# Extract Group "0" claster
cluster_data[cluster_data["Cluster"] == 0]

      Age   Income  LoanAmount  CreditScore  YearsExperience  Cluster
2      46  44219.0     26530.0        781.0               26        0
8      36  25918.0     25041.0        777.0               29        0
22     55  75575.0      8608.0        561.0               28        0
23     19  45488.0     16050.0        550.0               30        0
24     38  74225.0      8758.0        825.0               35        0
...   ...      ...         ...          ...              ...      ...
4972   46  44947.0     12481.0        585.0               35        0
4983   38  63518.0     21170.0        681.0               23        0
4990   45  53173.0     16452.0        614.0               24        0
4992   66  45575.0     32748.0        803.0               39        0
4998   53  58513.0     12373.0        813.0               23        0

[1471 rows x 6 columns]

In [42]:
# Extract Group "3" claster
cluster_data[cluster_data["Cluster"] == 2]

      Age   Income  LoanAmount  CreditScore  YearsExperience  Cluster
0      56  48353.0     31258.0        675.0               20        2
1      69  57462.0     23262.0        586.0                6        2
2      46  44219.0     26530.0        781.0               26        2
32     59  52315.0     21273.0        823.0                8        2
36     64  52307.0     26458.0        735.0               24        2
...   ...      ...         ...          ...              ...      ...
4966   49  30826.0     29351.0        649.0               22        2
4981   68  52185.0     17476.0        759.0               11        2
4990   45  53173.0     16452.0        614.0               24        2
4992   66  45575.0     32748.0        803.0               39        2
4998   53  58513.0     12373.0        813.0               23        2

[990 rows x 6 columns]

In [43]:
# Groups check

cluster_data["Cluster"].value_counts()

Cluster
3    1021
2     990
4     989
1     808
0     784
Name: count, dtype: int64

In [44]:
# Statystical summarisation for claster 3
cluster_data[ cluster_data["Cluster"] == 3].describe()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Cluster
count,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.0
mean,29.158668,49052.377081,19992.919687,582.553379,29.761998,3.0
std,7.500608,14906.224673,7870.353214,143.611159,6.149220,0.0
min,18.000000,6735.000000,45.000000,301.000000,15.000000,3.0
25%,23.000000,39070.000000,14285.000000,468.000000,25.000000,3.0
50%,28.000000,48956.000000,19982.000000,587.000000,30.000000,3.0
75%,35.000000,59369.000000,25347.000000,691.000000,35.000000,3.0
max,48.000000,95929.000000,47185.000000,849.000000,39.000000,3.0